name: Merge miscellaneous files
on: [push]
jobs:
  check-modified-since:
    runs-on: ubuntu-latest
    outputs:
      run-cri: ${{ steps.check-if-modified-in.outputs.run-cri }}
      run-ecc: ${{ steps.check-if-modified-in.outputs.run-ecc }}
      run-commit: ${{ steps.check-if-modified-in.outputs.run-commit }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: check-if-modified-in
      run: |
        git diff --name-only HEAD^ HEAD > files.txt
        while IFS= read -r file
        do
        	if [[ $file == "CRI/Lezioni"* ]]; then
            echo "New lesson found in CRI: $file"
        		echo "::set-output name=run-cri::true"
        		echo "::set-output name=run-commit::true"
        	else
        		if [[ $file == "ECC/Lezioni"* ]]; then
            echo "New lesson found in ECC: $file"
        		echo "::set-output name=run-ecc::true"
        		echo "::set-output name=run-commit::true"
        		fi
        	fi
        done < files.txt

  merge-notes-cri:
    runs-on: ubuntu-latest
    needs: check-modified-since
    if: needs.check-modified-since.outputs.run-cri == 'true'
    steps:
    - name: install-required-packages
      run: sudo apt-get install -y poppler-utils
    - name: clear-folders-internals
      run: rm -f CRI/Lezioni.pdf
    - name: cri-merge-lesson-notes
      run: pdfunite CRI/Lezioni/*.pdf CRI/Lezioni.pdf
    - name: cri-commit-new-file
      run: |
        git config --local user.email "unipi-informatica@github.com"
        git config --local user.name "UniPi Informatica Workflow"
        git add CRI/Lezioni.pdf
        git commit -m "Aggiornato il file."

  merge-notes-ecc:
    runs-on: ubuntu-latest
    needs: check-modified-since
    if: needs.check-modified-since.outputs.run-ecc == 'true'
    steps:
    - name: install-required-packages
      run: sudo apt-get install -y poppler-utils
    - name: clear-folders-internals
      run: rm -f ECC/Lezioni.pdf
    - name: merge-lesson-notes-ecc
      run: pdfunite ECC/Lezioni/*.pdf ECC/Lezioni.pdf
    - name: ecc-commit-new-file
      run: |
        git config --local user.email "unipi-informatica@github.com"
        git config --local user.name "UniPi Informatica Workflow"
        git add ECC/Lezioni.pdf
        git commit -m "Aggiornato il file."

  commit:
    runs-on: ubuntu-latest
    needs: [merge-notes-cri, merge-notes-ecc]
    if: needs.check-modified-since.outputs.run-commit == 'true'
    steps:
    - name: force-commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true