name: MAIN
on: [push]
jobs:
  check-modified-since:
    runs-on: ubuntu-latest
    outputs:
      run-merge: ${{ steps.check-if-modified-in.outputs.run-merge }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: check-if-modified-in
      run: |
        ls
        git diff --name-only HEAD^ HEAD > files.txt
        while IFS= read -r file
        do
        	if [[ $file == "CRI/Lezioni"* ]]; then
            echo "New lesson found in CRI: $file"
        		echo "::set-output name=run-merge::true"
            break
        	else
        		if [[ $file == "ECC/Lezioni"* ]]; then
              echo "New lesson found in ECC: $file"
        		  echo "::set-output name=run-merge::true"
              break
        		fi
        	fi
        done < files.txt

  merge-notes:
    runs-on: ubuntu-latest
    needs: check-modified-since
    if: always() && ${{ needs.check-modified-since.outputs.run-merge == 'true' }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: install-required-packages
      run: sudo apt-get install -y poppler-utils
    - name: setup-env
      run: echo "::set-env name=VERSION::$(echo $(date '+%Y-%m-%d'))"
    - name: cri-merge-lesson-notes
      run: pdfunite CRI/Lezioni/*.pdf CRI-Lezioni.pdf
    - name: ecc-merge-lesson-notes
      run: pdfunite ECC/Lezioni/*.pdf ECC-Lezioni.pdf
    - name: publish-notes
      uses: ncipollo/release-action@v1
      with:
        prerelease: false
        artifacts: "CRI-Lezioni.pdf,ECC-Lezioni.pdf"
        tag: "v${{ env.VERSION }}"
        token: ${{ secrets.GITHUB_TOKEN }}